# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Github Package Publish

on:
  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    #needs: [analyze]
    permissions: 
      contents: read
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: bichojp
          settings-path: ${{ github.workspace }}

      - name: Build with Maven
        run: mvn -B package --file pom.xml
      
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: jpprueba
          retention-days: 1
          path: |
            target/*
    
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    permissions: 
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: bichojp
        settings-path: ${{ github.workspace }}
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v4
      with:
        repositories: '[{"id":"githubjp", "name":"GitHub wecoderg Apache Maven Packages", "url":"https://maven.pkg.github.com/bichojp/*", "releases":{"enabled":"true"}, "snapshots":{"enabled":"true"}}]'
        servers: '[{ "id": "githubjp", "username": "bichojp", "password": "${{ secrets.REPOSITORY_TOKEN }}" }]'
        active_profiles: '[ "githubjp" ]'
        
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: jpprueba
        path: ./target/
    
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s /home/runner/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ secrets.REPOSITORY_TOKEN }}
